### ISSUE TITLE
Apresenta um bug no ao obter os valores do segmento - 

### ISSUE THREAD

**Issue by valterlobo** [helloticket/superfile#2]
Tentando obter um valor, exemplo CPF ou CNPJ no arquivo de retorno do teste CNAB400 do itaú , e retornado toda a linha do registro. 

o trecho de código foi adicionado no  "TestRetornoItauCnab400Cobranca" , após a leitura do arquivo : 	
retorno := arquivo.Read()

  valor := retorno.Segmentos()[0].Valores["numero_inscricao"] // BUG retornado a linha e não o registro. 
  fmt.Println( valor)
  fmt.Println( retorno.Segmentos()[0].Nome)

Encontrei o erro na linha do arquivo comparando com o decode do cnab240 -> https://github.com/helloticket/superfile/blob/d4e94aa6d5feb0f0b5d9d794a81481e925bef436/file/retorno_cnab400_file.go#L60

Na linha 60 - substituir  : `valores[l.Name] = l.Value`  por: `valores[l.Name] = r.decoder.Decode(l.Block, l)`

**Comment by helderfarias** [comment]
Correção aplicada. Muito obrigado.
